### ISSUE TITLE
分页点之间距离

### ISSUE THREAD

**Issue by wtbwtb332711** [lztbwlkj/MSCycleScrollView#1]
能否做成这个样式呢，选中页面的点与两边的距离跟其他的距离是一样的呢
![image](https://user-images.githubusercontent.com/25545536/53381139-bbd47f80-39aa-11e9-9018-f816b1eef778.png)

**Comment by Bretra** [comment]
去找个第三方pagecontrol就好了

**Comment by milletpeak** [comment]
很抱歉这么晚才回复你！！今天更新了0.0.2的版本，对PageControl稍作调整。你可更新试用，使用方法可查看Demo
